using Microsoft.CodeAnalysis;
using System.Text;
using UniTyped.Generator.MaterialViews;
using UniTyped.Generator.TypedViews;

namespace UniTyped.Generator
{
    public static partial class UniTypedGenerator
    {
        public static string? Execute(Compilation compilation, IUniTypedCollector collector)
        {
            var assembly = compilation.AssemblyName;
            if (assembly == null) return null;

            if (compilation.ReferencedAssemblyNames.All(a => a.Name != "UniTyped")) return null;

            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine($"// <auto-generated />");
            sourceBuilder.AppendLine($"// Assembly {assembly} {DateTime.Now}");
            sourceBuilder.AppendLine("#if UNITY_EDITOR");
            sourceBuilder.AppendLine("class UniTypedGeneratedTracker {}");

            UniTypedGeneratorContext? context = null;
            try
            {
                context = new UniTypedGeneratorContext(compilation, collector);

                TypedViewGenerator.GenerateViews(context, sourceBuilder);

                sourceBuilder.AppendLine("#endif");
                
                MaterialViewGenerator.GenerateViews(context, sourceBuilder);
            }
            catch (Exception e)
            {
                sourceBuilder.AppendLine();
                sourceBuilder.AppendLine("/*");
                sourceBuilder.AppendLine($"{e.GetType().Name}: {e.Message}");
                sourceBuilder.AppendLine(e.StackTrace);
                sourceBuilder.AppendLine("*/");
                sourceBuilder.AppendLine();
            }

            return sourceBuilder.ToString();
        }

    }
}